# Python 이미지 사용
FROM python:3.12-slim

# 환경 변수 설정
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 8000
COPY . .

CMD ["sh", "-c", "python manage.py migrate && exec gunicorn --bind 0.0.0.0:8000 main.wsgi"]