# Python 이미지 사용
FROM python:3.12-slim

WORKDIR /app

# 필요 패키지 설치
COPY . .
RUN pip install --no-cache-dir -r requirements.txt

# 환경 변수 설정
ENV PYTHONUNBUFFERED 1

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "main.wsgi"]